# Site settings
title: Kim Mido's Clutter Libary.
description:
google_analytics:
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://samsik0518.github.com # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kim Mido
user_description: I'm a Web Developer, Writer, and Artist.
user_title: Kim Mido's Clutter Libary.
email: samsik0518@gmail.com
twitter_username: walwalmungmung9
github_username:  samsik0518
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
